version: '3.8'

services:
  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - 80:80
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server

  server:
    container_name: server
    restart: unless-stopped
    build: ./server
    ports:
      - 5001:5001
    environment:
      DEV_DB_USER: postgres
      DEV_DB_PASS: root
      DEV_DB_DATABASE: mern_profile_page
    volumes:
      - ./server/src:/app/src
      # - ./server/src/uploads:/app/src/uploads
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: mern_profile_page
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
