### user login
POST http://localhost:5001/api/users/login
Content-Type: application/json
{
  "email":"test@test.com",
  "password": "123456"
}

### get data for front page
GET http://localhost:5001/api/users/get-front-profile

### get user profile for back page **require token
GET http://localhost:5001/api/users/profile
Content-Type: application/json
{
  token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTU3YWE0Mzg1MWQ1MTNmMGRmNzlmNWQiLCJpYXQiOjE2MzQyNTQ2NzMsImV4cCI6MTYzNjg0NjY3M30.kTkeBY1ov_LLh6Sxawy26l_Y7IH0mIgiaB5S2Hw1xIA"
}

### update user profile back page **require token
PUT http://localhost:5001/api/users/profile
Content-Type: application/json
{
  token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTU3YWE0Mzg1MWQ1MTNmMGRmNzlmNWQiLCJpYXQiOjE2MzQyNTQ2NzMsImV4cCI6MTYzNjg0NjY3M30.kTkeBY1ov_LLh6Sxawy26l_Y7IH0mIgiaB5S2Hw1xIA"
}

### update access for user, back page **require token
PUT http://localhost:5001/api/users/update-access
Content-Type: application/json
{
  token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTU3YWE0Mzg1MWQ1MTNmMGRmNzlmNWQiLCJpYXQiOjE2MzQyNTQ2NzMsImV4cCI6MTYzNjg0NjY3M30.kTkeBY1ov_LLh6Sxawy26l_Y7IH0mIgiaB5S2Hw1xIA"
}

### load portrait image, back page **no idea why this exists lol, **require token
GET http://localhost:5001/api/users/load-portrait

### load background image, back page **no idea why this exists lol, **require token
GET http://localhost:5001/api/users/load-background


### upload portrait image, back page **no idea why this exists lol, **require token
POST http://localhost:5001/api/users/upload-portrait
Content-Type: multipart/form-data

## load background image, back page **no idea why this exists lol, **require token
POST http://localhost:5001/api/users/upload-background
Content-Type: multipart/form-data