### get all places **require token I guess
GET http://localhost:5001/api/places
Authorization: Bearer ****

### get single place
GET http://localhost:5001/api/places/62
Authorization: Bearer ****

### create new place **require token
POST http://localhost:5001/api/places
Authorization: Bearer ****
Content-Type: application/json

{
  "company": "test company",
  "job": "test job",
  "year": "1900",
  "assignment": "test assignment",
  "show": true
}

### update existing place **require token
PUT http://localhost:5001/api/places/62
Authorization: Bearer ****
Content-Type: application/json

{
  "company": "update company",
  "job": "update job",
  "year": "1900",
  "assignment": "update assignment",
  "show": true 
}

### delete place **require token
DELETE http://localhost:5001/api/places/9
Authorization: Bearer ****
