### get all projects **require token I guess
GET http://localhost:5001/api/projects/
Authorization: Bearer ****

### get single project
GET http://localhost:5001/api/projects/50
Authorization: Bearer ****

### create new project **require token
POST http://localhost:5001/api/projects/
Authorization: Bearer ****
Content-Type: application/json

{
  "name": "test company",
  "url": "test job",
  "repo": "1900",
  "image": "test",
  "description": "test assignment",
  "show": true
}

### update existing project **require token
PUT http://localhost:5001/api/projects/6
Authorization: Bearer ****
Content-Type: multipart/form-data 
{
  "company": "update company",
  "job": "update job",
  "year": "1900",
  "assignment": "update assignment",
  "show": true
}

### delete project **require token
DELETE http://localhost:5001/api/projects/6
Authorization: Bearer ****

### upload project image **require token
POST http://localhost:5001/api/projects/upload-image-project/:projectId
Content-Type: multipart/form-data

### upload project image **require token
GET http://localhost:5001/api/projects/load-image-project/:projectId