### get all projects **require token I guess
GET http://localhost:5001/api/projects/get-all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5OTA3Njc3NiwiZXhwIjoxNzAxNjY4Nzc2fQ.1L2HH5DEaf-1HrN287OeLJElfIZ6lQ34lt_VaT2L7AM 

### get single project
GET http://localhost:5001/api/projects/get-project/:projectId

### create new project **require token
POST http://localhost:5001/api/projects/new-project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5OTA3Njc3NiwiZXhwIjoxNzAxNjY4Nzc2fQ.1L2HH5DEaf-1HrN287OeLJElfIZ6lQ34lt_VaT2L7AM 
Content-Type: application/json

{
  "company": "test company",
  "job": "test job",
  "year": "1900",
  "image": "test",
  "assignment": "test assignment",
  "show": true
}

### update existing project **require token
POST http://localhost:5001/api/projects/update-project/:projectId
Content-Type: multipart/form-data 
{
  "company": "update company",
  "job": "update job",
  "year": "1900",
  "assignment": "update assignment",
  "show": true
}

### delete project **require token
POST http://localhost:5001/api/projects/delete-project/:projectId

### upload project image **require token
POST http://localhost:5001/api/projects/upload-image-project/:projectId
Content-Type: multipart/form-data

### upload project image **require token
GET http://localhost:5001/api/projects/load-image-project/:projectId