### get all skills **require token I guess
GET http://localhost:5001/api/skills
Authorization: Bearer ****

### create new skill **require token
POST http://localhost:5001/api/skills
Authorization: Bearer ****
Content-Type: application/json

{
  "name": "test company",
  "value": "100",
  "show": true
}

### update existing skill **require token
PUT http://localhost:5001/api/skills/5
Authorization: Bearer ****
Content-Type: application/json

{
  "name": "update skill test",
  "value": "90",
  "show": true
}

### delete skill **require token
DELETE http://localhost:5001/api/skills/4
Authorization: Bearer ****
