### get data for front page
GET http://localhost:5001/api/users/get-front-profile

### get user profile for back page **require token
GET http://localhost:5001/api/users
Authorization: Bearer ****
Content-Type: application/json

### update user profile back page **require token
PUT http://localhost:5001/api/users
Authorization: Bearer ****
Content-Type: application/json

{
  "name": "updated",
  "lastName": "lastName",
  "github": "github.com",
  "linkedin": "linkedin.com",
  "phone": "updated phone",
  "bio": "updated biosd",
  "profession": "one, two, three, updated"
}
